/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./../../src/components/Counter.vue')['default']
    Dropdown: typeof import('./../../src/components/Dropdown.vue')['default']
    HelloWorld: typeof import('./../../src/components/HelloWorld.vue')['default']
    'IEp:arrowLeftBold': typeof import('~icons/ep/arrow-left-bold')['default']
    'IEp:arrowLerfBold': typeof import('~icons/ep/arrow-lerf-bold')['default']
    'IMdi:accountBoxMultiple': typeof import('~icons/mdi/account-box-multiple')['default']
    'IMdi:arrowLeftBold': typeof import('~icons/mdi/arrow-left-bold')['default']
    Navigation: typeof import('./../../src/components/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
